// User actions
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';

// Entity actions
export const FETCH_ENTITIES_REQUEST = 'FETCH_ENTITIES_REQUEST';
export const FETCH_ENTITIES_SUCCESS = 'FETCH_ENTITIES_SUCCESS';
export const FETCH_ENTITIES_FAILURE = 'FETCH_ENTITIES_FAILURE';

export const ADD_ENTITY_REQUEST = 'ADD_ENTITY_REQUEST';
export const ADD_ENTITY_SUCCESS = 'ADD_ENTITY_SUCCESS';
export const ADD_ENTITY_FAILURE = 'ADD_ENTITY_FAILURE';

export const UPDATE_ENTITY_REQUEST = 'UPDATE_ENTITY_REQUEST';
export const UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITY_SUCCESS';
export const UPDATE_ENTITY_FAILURE = 'UPDATE_ENTITY_FAILURE';

export const DELETE_ENTITY_REQUEST = 'DELETE_ENTITY_REQUEST';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAILURE = 'DELETE_ENTITY_FAILURE';

export const DELETE_MANY_ENTITIES_REQUEST = 'DELETE_MANY_ENTITIES_REQUEST';
export const DELETE_MANY_ENTITIES_SUCCESS = 'DELETE_MANY_ENTITIES_SUCCESS';
export const DELETE_MANY_ENTITIES_FAILURE = 'DELETE_MANY_ENTITIES_FAILURE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_ENTITY_ERROR = 'CLEAR_ENTITY_ERROR';

// Theme actions
export const SET_THEME = 'SET_THEME';